### ISSUE TITLE
towards a remote-code v1.0

### ISSUE THREAD

**Issue by dkebler** [anoff/remote-code#5]
Andreas,

I've got some rsync based bash scripts that I use when developing on RPI so I can develop in Atom on my dev machine and have them run (with nodemon) on the RPI very similar to remote-code but not nearly as seamless.  BTW, I run ubuntu 16.04 on both.
https://github.com/dkebler/syncd

I usually have dependencies I am working on at the same time so I set up a separate syncd process to sync them directly to their corresponding folder in node_modules on the RPI project (nodemon now supports watching above the root of project).   Too I run a local registry using verdaccio and the RPi's .npmrc is pointed there first to find my other modules under development before looking at npm.

I see you have been silent for a year on this repo.  Still I see what you have done as a improvement over my workflow and more than that I am looking for slick way to deploy code to RPI and launch multiple socket based processes that can talk back to the remote master which launched them,  basically one upping remote-code for dev to remote-code for production.

If you still have time/interest in this project i'd be interested in with working with you otherwise I'll just fork what you've done and be one my way.  Either way I appreciate what you have done.  It's given me a head start including that that you've used es6 classes!  I now use the esm module so have dropped cjs and with node 10+ almost all es6 is supported natively.

**Comment by anoff** [comment]
Hey @dkebler 

I would definitely love to collaborate on that. Tbh remotecode was just a tool I needed at the time because I got fed up with running bash commands.. Never got around to actually implementing some things I need (e.g. ignore file globbing / .gitignore).

Regarding module API I would prefer the package to be at least node 8+ (maybe even 6). If you know how to transpile in the build chain before publishing I would be fine with rewriting the codebase though.

**Comment by anoff** [comment]
@dkebler are you still interested in this or can I close the issue?

**Comment by anoff** [comment]
let me know if you want to pick this up again :)

**Comment by dkebler** [comment]
haven't forgotten and now that  "winter is coming" and I am back to my project that could make use of this.  So I'll fork and clone in anticipation of a pr.

**Comment by dkebler** [comment]
So...got a bunch of improvements in a day of putzing around. Fun!

here is the "new" branch at my fork.
https://github.com/dkebler/remote-code/tree/new

What I did is pretty rough but it works ok.  You can check out latest commit if you want.  Beyond the changes it needs some more error checking especially in async calls and I'm going to change to esm imports.  Also need to set some timeouts on promises in case they get hung remotely.   Probably think of some other changes/additions now that I am familiar with the code (nice job, easy to follow)

CHANGES:

Now uses node-config for startup from a config file (in my case a yaml)
https://github.com/lorenwest/node-config  so now can be as simple as typing "remotecode" at the prompt from the root of source repo.  config file(s) live in /config of the source directory

Now works with a key-agent and also I found a solution to allow the text password access too using sshpass (haven't tested it yet)

I modified the cli and remotecode class a bit so that one can use the config file from the cli or direct from a remotecode instance.  Thus the defaults get set in remotecode class constructor and no longer in the cli.

Added a few other options
registry:  url of custom registry that will be used on install
key-agent: the environment variable holding the path to the agent socket,  there are a couple names tried by default 

here is a sample config file
```
#commented keys indicate their default
options:
  target: /opt/relays
  #install: 'yarn'
  #registry:    # used for grabbing from custom registry first
  #source: .
  #start: 'nodemon .'  # pm2 could be used as well
  #verbose: false
  ssh:
    host: relays.kebler.net
    # port: 22
    username: sysadmin
    # need one of these three.  If none given will try to find the keyagent at some typical names
    #keyfilePath: 
    #agent:  # the environment variable name of your ssh agent socket, defaults are SSH_AUTH_SOCK and SSH_AGENT_SOCK
    #password:  # for non keyfile access
    # keepaliveInterval: 500
    # readyTimeout: 2000
```
